all:	Teste_Matriz.c ../Sources/Dados_Voo.c ../Sources/Item_Matriz.c ../Sources/Lista_de_Voos.c ../Sources/Matriz_Voos.c
	clang Teste_Matriz.c ../Sources/Dados_Voo.c ../Sources/Item_Matriz.c ../Sources/Lista_de_Voos.c ../Sources/Matriz_Voos.c
